### ISSUE TITLE
colab demo & some issues

### ISSUE THREAD

**Issue by ykk648** [enriccorona/LVD#2]
colab demo:
https://colab.research.google.com/drive/1z514XyVD-TAUwBBMGvbHHpe-yzVmpAqr?usp=sharing

issues:
1. https://github.com/enriccorona/LVD/blob/3c8164603c3402cd245ab8f25edea3c6d9f53f8a/utils/image_fitting.py#L494  path error
2. the script seems only receive mask-image pair but not image-only, i'm wondering where did you get those maskes so I can test in wild pics.

**Comment by enriccorona** [comment]
Hi, thanks for your comment and creating the colab! Thanks for mentioning the path error, we hadn't realise, they should be corrected now.

I also added a demo to run LVD from images without masks and without cropping or running any pre-processing. We use mediapipe to get the segmentation mask and preprocess the image accordingly. 
Let us know if you have any problems if you try it!

**Comment by ykk648** [comment]
thanks, got what I want
